Add the option to remove unparsable fonts
whtsky/font-rename pull request #11
Opened 2021-03-31 01:58 UTC by Zopolis4

This commit adds the option to remove unparsable fonts as opposed to printing an error message (not collections, due to the way the script handles them. working on that). It also adds support for creating further argparse arguments while keeping the sys.argv path variable intact.

2021-04-06 05:47 UTC, whtsky requested changes

2021-04-08 01:40 UTC, Zopolis4 commented on font_rename.py
>          for path in sys.argv[1:]:
I wasnt sure how to migrate those, so I left them there.

2021-04-08 01:40 UTC, Zopolis4 commented on font_rename.py
> +       unpack_ttc(filepath)
No idea, probably a typo, sorry.

2021-04-08 01:48 UTC, Zopolis4 commented on font_rename.py
> +parser.add_argument("-ru", "--remove-unparsable", dest="ru", action="store_true", help="When this option is enabled, unparsable fonts are removed instead of ignored")
Sure!

2021-04-08 02:16 UTC, Zopolis4 commented on font_rename.py
> +args, unknown = parser.parse_known_args()
When I tried that, it broke the script

2021-04-08 02:20 UTC, Zopolis4 commented on font_rename.py
> +            os.remove(filepath)
I'm not sure exactly which area of code you are referring to, are you suggesting I use `os.unlink` instead of `os.remove`? Or something else?

2021-04-08 03:37 UTC, whtsky commented on font_rename.py
> +args, unknown = parser.parse_known_args()
> it broke the script

Can you provide more info?

2021-04-08 03:37 UTC, whtsky commented on font_rename.py
> +            os.remove(filepath)
`filepath` is a [Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) object -- it has [unlink](https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink) method. You can use `filepath.unlink()`

2021-04-08 08:55 UTC, Zopolis4 commented on font_rename.py
> +args, unknown = parser.parse_known_args()
https://github.com/whtsky/font-rename/actions/runs/727960106

2021-04-08 09:11 UTC, Zopolis4 commented on font_rename.py
> +            os.remove(filepath)
Done

2021-04-08 09:44 UTC, whtsky commented on font_rename.py
> +args, unknown = parser.parse_known_args()
I think `rename_font` should accept a new argument `remove_unparsable` instead of referring to global variable `args`

2021-04-08 11:20 UTC, Zopolis4 commented on font_rename.py
> +       unpack_ttc(filepath)
Added space

2021-04-12 08:03 UTC, Zopolis4 commented on font_rename.py
> +args, unknown = parser.parse_known_args()
I am not sure how to do that

2021-05-11 04:04 UTC, Zopolis4 commented on font_rename.py
>          for path in sys.argv[1:]:
Done

2021-05-12 01:42 UTC, whtsky approved these changes
looks good overall

2021-05-12 01:42 UTC, merged